apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260622-004613-2r5zoa8nj4vx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260622-004613-2r5zoa8nj4vx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260622-004613-2r5zoa8nj4vx-service
            port:
              number: 80
