apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260622-004613-2r5zoa8nj4vx-service
spec:
  selector:
    app: enterprise-system-20260622-004613-2r5zoa8nj4vx
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
